// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Candidate = __t.object("Candidate", {
  candidateId: __t.u32(),
  name: __t.string(),
  totalPopularity: __t.f32(),
});
export type Candidate = __Infer<typeof Candidate>;

export const VoterGroup = __t.object("VoterGroup", {
  groupId: __t.u32(),
  name: __t.string(),
  populationWeight: __t.f32(),
});
export type VoterGroup = __Infer<typeof VoterGroup>;

export const VoterShare = __t.object("VoterShare", {
  combinedId: __t.string(),
  groupId: __t.u32(),
  candidateId: __t.u32(),
  sharePercent: __t.f32(),
});
export type VoterShare = __Infer<typeof VoterShare>;

