// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  combinedId: __t.string().primaryKey().name("combined_id"),
  groupId: __t.u32().name("group_id"),
  candidateId: __t.u32().name("candidate_id"),
  sharePercent: __t.f32().name("share_percent"),
});
